apiVersion: v1
kind: Secret
metadata:
    name: grafana
type: Opaque
stringData:
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:BB/qnmXGSiTkhUmxOV8=,iv:rvZie1Ynu9bCtEqSWQMKVklzG2Z/rWFolhZfK9Dylgg=,tag:izZncH7G6wWuNWIT7zJZSw==,type:str]
    ALERT_WEBHOOK_URL: ENC[AES256_GCM,data:t3IBMmAMtBhDmf4H/9lubQ6PpEl0kjxH8smePkW5s0uljV3M0K70dn8LO4rJ+mORaqJOosGXxJLQoXS89WEQuyRG3xeUkq/mcxnXuqaprMlChS3lY+LGjHhP5DUQ9vgycLrC00btJDdVMENLOQEIf/fbNdEvYU6Gtg==,iv:X3i65ixTe1vzhLo8lkYH5O8EIjGOfR+xUqhT4Y1Tfcs=,tag:MrEQnDfjFkOKyF2bobMr2w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cnU1L3lNQy9MdG8yOWR3
            R3VOd3p1Z1gzSTFGMERsb2JlMUhmcXRuN0NJCk0yVHJMVGp4WmFiTzZCL05pV0Fz
            YTlVWjAxWVp4YTFSWEdaMXVDTERnRFUKLS0tIHp2N0dsQTBOVVVwcmVlSEx4ZC9k
            RVhoSG9kamVGbzV4cFlkc1B4elgzdmcKDTL3N/occjkJ6KlUmzEBkA3NrFIACXet
            Xlx85l45Y/Sq5vhHMFpJLocx9d4gyrWgj2kufKIa+/CtCwwoJOoq5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s230vj65pqugtzgwt3d9rh0dymz80ucxt39aq6a8mt8egkp7yqeqpjawc6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T10:44:16Z"
    mac: ENC[AES256_GCM,data:4NBL6E/mhzXc5LWcwS77U17Yffe9n0u5MF8UMGoibktHg3xJsPuD6quTpOo1LDnT67pANfiZqx3gPl09qFWMrELhZMZ11xan/7oClQ5K8Dp8sQq3M9cljnIR63xmNFuI1faTq0yXv4isZx3j2xPMspvcIcLi49lLgiHh0AirElI=,iv:W/hynyA5q9DlGhbMqGNiKEbzE1c9VhjU5jlaY7I5G2U=,tag:xs31YM/WcAsfQWW0gjydvg==,type:str]
    version: 3.13.3
