apiVersion: v1
kind: Secret
metadata:
    name: siyuan
type: Opaque
stringData:
    SIYUAN_ACCESS_AUTH_CODE: ENC[AES256_GCM,data:SHcduGSWrQQ5dPChA+/FFL7QcUHo8v4sq77IcRgHcTk=,iv:fdy9/NRZHJrAJqga9vlbhebfNuZn6wW2Qquxzk7ou+E=,tag:g4KpPqj6gCXWMnh8tizulA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHOW9uMjBHTHZ1Q3FmUjBq
            amVHcWhwNnpWZWVzazVsM0VESkVxSXVWU0JvCmtyUDBZemFia1lILzdFdThPOWJO
            WnF2YStrOEw5RGZMeUNBS3ZWYUg0bHcKLS0tIEdsRmtNa1dUMkZzVGM3RzZpNTJO
            Nkxqa1RpY0hNUmRXbWJkOUVBaFpUckUKPvuEnw/R9rHTdNQu67pNE0qj8qFYtN/k
            PRixQp9p5TI0zL4CpzG47RLwTfeOQxgvEpx+eV5Q+S0x3cnafebVrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s230vj65pqugtzgwt3d9rh0dymz80ucxt39aq6a8mt8egkp7yqeqpjawc6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T07:19:17Z"
    mac: ENC[AES256_GCM,data:iPJ3zMz7TZ6SOc56NNkpMpJk2uXytPLvwPClC/mJTD2uWNa/hniGfA96nWAc7l2t25wCvyg+EAoKRRMrz+wUoy10+ValdTkWJQUSHaomE1J/kVGDENWm8TowA5OxiVBJVNbBiPeWjK1U+g67cPD6HknBjfNkCLALVyUiH1FwfUI=,iv:Iqhn/XwWZLHOrbJqADuOw0CflnHWBLHWrnMcI3DvXco=,tag:bnHhjMmjfqxmUvTeudaRBg==,type:str]
    version: 3.13.3
