apiVersion: apps/v1
kind: Deployment

metadata:
    name: immich

spec:
    replicas: 1
    strategy:
        type: Recreate
    selector:
        matchLabels:
            app: immich
    template:
        metadata:
            labels:
                app: immich
        spec:
            enableServiceLinks: false
            containers:
                - name: immich-db
                  image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
                  env:
                      - name: POSTGRES_DB
                        value: immich
                      - name: POSTGRES_USER
                        value: postgres
                  envFrom:
                      - secretRef:
                            name: immich
                  volumeMounts:
                      - name: immich-db
                        mountPath: /var/lib/postgresql/data
                  resources:
                      requests:
                          cpu: 100m
                          memory: 256Mi
                      limits:
                          memory: 1Gi
                  startupProbe:
                      exec:
                          command:
                              ["pg_isready", "-U", "postgres", "-d", "immich"]
                      periodSeconds: 2
                      failureThreshold: 60

                - name: immich-redis
                  image: docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
                  resources:
                      requests:
                          cpu: 50m
                          memory: 64Mi
                      limits:
                          memory: 256Mi
                  startupProbe:
                      exec:
                          command: ["valkey-cli", "ping"]
                      periodSeconds: 2
                      failureThreshold: 30

                - name: immich
                  image: ghcr.io/immich-app/immich-server:v3.1.0@sha256:b434cb9287eea1471c9974845914d4dd328c9c2d652e446ed4930f99944f0ceb
                  env:
                      - name: UPLOAD_LOCATION
                        value: /data/immich/library
                      - name: DB_DATA_LOCATION
                        value: /data/immich/db
                      - name: DB_HOSTNAME
                        value: localhost
                      - name: DB_DATABASE_NAME
                        value: immich
                      - name: DB_USERNAME
                        value: postgres
                      - name: REDIS_HOSTNAME
                        value: localhost
                      - name: IMMICH_MACHINE_LEARNING_URL
                        value: http://localhost:3003

                  envFrom:
                      - secretRef:
                            name: immich
                  ports:
                      - name: http
                        containerPort: 2283
                  resources:
                      requests:
                          cpu: 200m
                          memory: 512Mi
                      limits:
                          memory: 2Gi
                  volumeMounts:
                      - name: immich-library
                        mountPath: /data

                - name: immich-machine-learning
                  image: ghcr.io/immich-app/immich-machine-learning:v3.1.0@sha256:5a0839dc5303cd7215bcd2180a26aed3af41675aefb3e75e5157e9f10ad16e6e
                  env:
                      - name: UPLOAD_LOCATION
                        value: /data/immich/library
                      - name: DB_DATA_LOCATION
                        value: /data/immich/db
                  resources:
                      requests:
                          cpu: 200m
                          memory: 1Gi
                      limits:
                          memory: 4Gi
                  volumeMounts:
                      - name: immich-machine-learning
                        mountPath: /cache
            volumes:
                - name: immich-db
                  hostPath:
                      path: /var/data/local/immich/db
                      type: Directory
                - name: immich-library
                  hostPath:
                      path: /var/data/external/immich/library
                      type: Directory
                - name: immich-machine-learning
                  hostPath:
                      path: /var/data/external/immich/machine-learning
                      type: Directory
