apiVersion: v1
kind: Secret
metadata:
    name: immich
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:bET2t/ABx5w=,iv:wMCCapibszGrQnm86V4+3OIoPPksAejtudCiwTd4pgI=,tag:hBWbmA/Sr1NTnHtT1+oeMQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:z56TcHIU1GQ=,iv:hf2npXmUOML3V3I/y54GvSyaTon3MI/0CfVWjDxZWhk=,tag:SDkr9lDRCR55AD5La4My9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVWJic2RwdG9DNmVaUVB2
            VkZwQ1IxcUxUZnZ4N2JrWUFCNFBNeHJEWHhFCkhVTlczVkNSdGxrL1UzWnAyTmth
            RURQZy9kUFR3U3RpMktNL1YxMDFmY2MKLS0tIDlia09iTTlITDhRdk1ha3hobWEx
            eE9LQXdiUW8xemZOTzRoclk2MjdFRFUKW+ChhtePSjsCZCFFF03TsSZTpq0zagJk
            cwePH8ICnA+EIgfrvWGyVK8Ang4PbA0bT6WMqABGq9OtX3Y8P4MipA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s230vj65pqugtzgwt3d9rh0dymz80ucxt39aq6a8mt8egkp7yqeqpjawc6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T07:19:17Z"
    mac: ENC[AES256_GCM,data:He8Oith2n1ZMvGbJ6gOAGHV/Dl/QUctAum1fY0azq3n2VF3LBxO9I89AYJFlVx8/DClFcoq8vbzb5eRbKSfCOPpRX1aAR7/ZAkWyzf1QVTx49MT1bSX9VO4ym3CLI+cIvqqnuYJ4rJh7WLEMgR/b48+E6oWWyeyL0IcG3JoIVj8=,iv:hJL6kN+K61EsTkDeBFBFQfhctZheLdq43SVcQ0KXMuQ=,tag:pQHUfSDut0yJxts4FmWj0w==,type:str]
    version: 3.13.3
