apiVersion: v1
kind: Secret
metadata:
    name: flux-gpg-public-keys
    namespace: flux-system
type: Opaque
stringData:
    wacky.asc: LS0tLS1CRUdJTiBQR1AgUFVCTElDIEtFWSBCTE9DSy0tLS0tCgptRE1FYXBnckNoWUpLd1lCQkFIYVJ3OEJBUWRBcUdta0x5dXR5OWcvcTg5b3RJWjRFakhYS2cyZDAxWG41aDNiCitWQjNLZTYwQlhkaFkydDVpSk1FRXhZS0FEc1dJUVRPQ1N1VWo5WGU0cDF4SkZCaGZOR2ZhNXhkTHdVQ2FwZ3IKQ2dJYkF3VUxDUWdIQWdJaUFnWVZDZ2tJQ3dJRUZnSURBUUllQndJWGdBQUtDUkJoZk5HZmE1eGRMeFg5QVA0awpzQi9XTml4b1BBUzBkc3FRcHFyazJJUWlndEpNaEIralZ6cXg0T0lDSGdFQW1tZ2lqOVpEb3ZTK0ptNGJ6LzVXCmhKWVd0Y1ZuRCsrZlVadjF0U3kwcXdzPQo9ejZSUwotLS0tLUVORCBQR1AgUFVCTElDIEtFWSBCTE9DSy0tLS0tCg==
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
    name: flux-system
    namespace: flux-system
spec:
    interval: 1m
    url: https://github.com/wacky-homes/server.git
    ref:
        branch: main
    verify:
        mode: HEAD
        secretRef:
            name: flux-gpg-public-keys
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: applications
    namespace: flux-system
spec:
    interval: 5m
    path: ./apps
    prune: true
    wait: true
    timeout: 5m
    sourceRef:
        kind: GitRepository
        name: flux-system
    decryption:
        provider: sops
        secretRef:
            name: sops-age
