apiVersion: v1
kind: Secret
metadata:
    name: immich
    namespace: default
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:jFsnk3l5TRQ=,iv:zDe7kPSbt1TT1qu8s6RrSqV7sJ5b/GKsoVDx16ybn3M=,tag:dOFC93nYHMcXeos0c4O8bg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:4TMZdLHvLGk=,iv:bQ/BcRxmS5ToW23oXp1uSL7TfWsc6ixH1/YebeB86WQ=,tag:jBJAHiKEBs1WC7V6ss5IOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MENXT001RTZWMXh2dVQv
            VUVBYzVaMXRiYVM2Sm5MS0lYeFJoMmVxakJ3Cmh4TEhXdXBlbGRua25VUTFseU9k
            a0dMWWczcVpxbmZMTlFXbHZIZ1pNMFUKLS0tICtxZ21MOUJPMjBFNm5FRVpnajlQ
            Zmh6ZUxCQitIN2ZzcGNMY0xZWCt6WHMKdGXCKz8CtORT+wu5/ZZz8RPQzh5qJ1rs
            a8ILSCaBqZ6lAwp/W4DsOhzK9uvARLz4pyW3emGesC+H0y8Xdn8GGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s230vj65pqugtzgwt3d9rh0dymz80ucxt39aq6a8mt8egkp7yqeqpjawc6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T17:12:45Z"
    mac: ENC[AES256_GCM,data:50QzWi1t/dAh5eIRoc9DpSYTX5rtCk9tJjbLlZjcpjMaDHVDRXZ1XtBJ13dDC3NbRO3FRv3PHPbl1iLG6duCCkZNkyUJOYqTQF4JaAWxS95eNgBQm0ZldLGv4wJB7clHZPebVWamya81X9b8RXBlA+2Ud61Dibj8c83V+QQ21bk=,iv:P7K616cXyLwSC/LONRmCyTgjgRomIqysjauTN+V5IyM=,tag:4vkNZlk2SvYmrjihL1K2aQ==,type:str]
    version: 3.13.3
