apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:13mdtxeDR7QQKlM3HIwGH6NPuJKSEpkBpqNA4Df5ivN4hspkEV6K9agvavrJzkuDuCRHQhz0f7QSHGhBKU65qOo0yHJdGgbcga43mm10VIFETeISbLOr8CfLaSDHL496FsNk2SvQ+JaDYp6yR6KLJtBrok9GZE7wpLcQALPQzTbPdKgnv3X2Xk9Okf/1MiaBl5G+/tOruNqeSVqYswPN3GbcIgJRJaWpyuD9JrulVLnOiMFjcNDqQQ==,iv:HJKt9CgPPypATLU7s7sk3aogWr96QDzadDigEfHykx8=,tag:FmyHGCon4nGbBW4ZCBSG/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWWtpdjRaYk1yaFJCRkZz
            MUUyRXlLR2JObkkyY2lmMzNhRGtJNzNTRkhrCmpaQTh6eVIvd2U4czE4NUM5b205
            Q3hNSGtqTmUrdGhiRWxaTW4wblFJdEEKLS0tIGF6dzl1RldHZEJ1ajF2K25VVkpR
            cHpJSG9acEkrQk54cGw0V09oeWpMVlUKeGYu+ZI0fAFmELAKXtpsgzRQhYHcc1bM
            Vdv7XOQT03cqUOUNWxrCsYDSGYUg6Pk0pqMZGuqnazuOaOi0yse78Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s230vj65pqugtzgwt3d9rh0dymz80ucxt39aq6a8mt8egkp7yqeqpjawc6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T07:19:17Z"
    mac: ENC[AES256_GCM,data:okU3J2QTFf/hbusmvOQm+dWtf5s+bYxE3sJpIauVQdI4KlbtqyBTT4T2bgjBVF//vx7I4vjoZwR++Ngemp2MTi7cVLahgTnH/z241eHTESRXJ8jYfKozWWqUX1zTJXqyy4S3c8Zc4e8tSz2MiIolrmq39YvhwozJJ1KB0l6ydhs=,iv:wNX7RVA0Q5/NYGpUcoL56qFbZCUDskOjDWnJe/OjH0A=,tag:iXOpt3FwGw2n2O7nWJfatw==,type:str]
    version: 3.13.3
