apiVersion: v1
kind: Secret
metadata:
    name: whoami
    namespace: default
type: Opaque
stringData:
    API_TOKEN: ENC[AES256_GCM,data:9nvlrw==,iv:WaraovAR0ErqcGelRFVeLuTu3ca4Wr/hdCS+yAxouKs=,tag:w9IcA9hl1xP300RcOdtUzw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1THJKS1prenVpdzArL1Fx
            WDJybzQ4Rm0zR3RFWlJlRjZDRlZ2ZmZ4QXk4Cjg2L3h0YW5zY2J3WWtlcC9lWFhj
            RXN2Z3A4OE9pZ3RScUxyOWcyODZaV28KLS0tIGM1KzNqSXliZ2lsVGRGR3Y5SEhu
            VEwzM2VKcUxHSWpOOG12Nk12c21id2sKTjUuAT0M7i3glBguv7Qfz4vYShB1froF
            VtQnDcQg/5l3QawQTGnPs/5P3oq2YN3jINpsG+C71fFXL4S6d763nw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s230vj65pqugtzgwt3d9rh0dymz80ucxt39aq6a8mt8egkp7yqeqpjawc6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T13:10:46Z"
    mac: ENC[AES256_GCM,data:6Ac/ZkRp+62W667DiP8c+2wd8vx3ooDO8t2p8RQEANa7uDv16622c4xfaFvP3N0Tbcw4gt47+sRw4dHi2Dl4A96iRlQZ1E8vYbLkpiSyN0dDFRPo+GVoUEQTr8RAPYLfib/TaUnD+c1De/ZUrMHa6UAPIAh0/rYZs24a9oAeAEc=,iv:qWJ1MhqOfqn552NaPRAaSue8LrI89/dWDo0+O585ZBs=,tag:Gpg8C6a7oPWozIPM1tGJkw==,type:str]
    version: 3.13.3
