apiVersion: apps/v1
kind: Deployment

metadata:
    name: vaultwarden

spec:
    replicas: 1
    strategy:
        type: Recreate
    selector:
        matchLabels:
            app: vaultwarden
    template:
        metadata:
            labels:
                app: vaultwarden
        spec:
            enableServiceLinks: false
            containers:
                - name: vaultwarden
                  image: docker.io/vaultwarden/server:1.37.2@sha256:094b5689ed81549bd293418395c7cf495ae9d960fc2d4928cef2083ef913d912
                  ports:
                      - name: http
                        containerPort: 80
                  resources:
                      requests:
                          cpu: 50m
                          memory: 128Mi
                      limits:
                          memory: 512Mi
                  volumeMounts:
                      - name: data
                        mountPath: /data
            volumes:
                - name: data
                  hostPath:
                      path: /var/data/local/vaultwarden
                      type: Directory
