apiVersion: v1
kind: Service

metadata:
    name: vaultwarden

spec:
    selector:
        app: vaultwarden
    ports:
        - name: http
          port: 80
          targetPort: http
    type: ClusterIP
