apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
    name: siyuan
    namespace: default
    annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web

spec:
    ingressClassName: traefik
    rules:
        - host: notes.wacky.homes
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: siyuan
                            port:
                                name: http
        - host: notes.wacky.local
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: siyuan
                            port:
                                name: http
