apiVersion: v1
kind: Secret
metadata:
    name: siyuan
    namespace: default
type: Opaque
stringData:
    SIYUAN_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Cnd+NcJEv7YFiD3V1UU2zdtM9FOcQmqVypU7budJkC5ZDsA=,iv:uVQSCE7+BBH8WkOySpwytCSmBHkLa3l1fKXfNYPdyfo=,tag:B7TwROyKROKq2nhi25qV6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1a0w0TWVJN1FyT0MzWHRa
            TjJmT0dsRXF2UlZFNHdwNm1tMHQ2bGRvd1ZBCkUrMFM5M3NtczhlbytFbWRTQWpO
            aElNSVlDU0ZCTUhVdGlOcVZjck9tVDAKLS0tIGtCeUZNaVFOQ3dWUTNsVHZxOE96
            ODdhdkxQeUpaYisrL0NnaDI2RXVyakkKuFSXBWFy7OL+XhQcekDfvVAGRrR5xfxp
            4e6bnV8CaWMwgqq4FV+7deAeq/ATuFMIsIk0Zlw71F84r/zmiipNhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s230vj65pqugtzgwt3d9rh0dymz80ucxt39aq6a8mt8egkp7yqeqpjawc6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T17:34:21Z"
    mac: ENC[AES256_GCM,data:OvqtcH4LlvD5XLEuhRdpeDamvcPV15Z2hmUaiC3kOUstoeCuVFH2mMZXLKII6UhUkRGDGMiaFwaSxKLsqOnx1AwvuZB0glibPBqNIZqnWwS1nst0C4S1EBrYBbIrVLJjwKBhOIcTIe5K1C+4d6ic4mU3lAL2r41C52/X7r/cbOs=,iv:NUD8gyPvK0z9i/1XIJPR25DOnsVzwbqW6aPcLqFrGz0=,tag:p+uxwzAy5tZ07sl4GhpLEQ==,type:str]
    version: 3.13.3
