apiVersion: v1
kind: Secret
metadata:
    name: immich
    namespace: default
type: Opaque
stringData:
    SIYUAN_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:/7Oof58Eb7jb8jQwU2ag+sxgh6qm75AVqFZf0xyAdpogwW8=,iv:rVLT1MVke24kXfDt8M0Qu2Ax+FFiwXReVWrePDxzFjY=,tag:l+P5RUHbxsdw9HHrKDjgAw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UVAxTHRMd1NUdzhHRmNt
            NjQvU1lUWmNGNlJFRzNxUXVsa3UxbzErejFRCm1Hb3dsWWJhWG8yU2hKc0xsNlQv
            WTFUbUR5UmZmOUdCL3B5UEREMnpUQ00KLS0tIEZ5ajRvY0dVYVhlV0crdC8wN1ZB
            amdvb1ZqdVZRR3F3OC9ObmZMTHBkTGMK5QDflKwcLqsb12Y/JAKLHJw0w4CweOrt
            yLI47C34cQc2rqrc2TIJLBxcbwxzl0ngd4d40E59MXm9f2CbLgc8hw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s230vj65pqugtzgwt3d9rh0dymz80ucxt39aq6a8mt8egkp7yqeqpjawc6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T17:31:32Z"
    mac: ENC[AES256_GCM,data:7DlkUBa5mj+kTDj7KATNL/8OEC+NFGnUDJgAomXiXS+36W5rvtqPifiB5w+9Bq7DmcLSVgKPQ5LB+yBG9+gknsP1hSrUh/oM5teaMGt9ro2hs4l2pWqiPXeleQbuwXb7qoeo4OmyJEx0gVWBioOXKczZVOZqE55zTBtG7L8Gd1I=,iv:0PRzXVyWbX7Z+Cc3Bx09s/cp8tO2VpGt7ZQMutxuSOo=,tag:hjMIsxBiHDFOUARZVprBkw==,type:str]
    version: 3.13.3
