apiVersion: v1
kind: Secret
metadata:
    name: siyuan
    namespace: default
type: Opaque
stringData:
    SIYUAN_ACCESS_AUTH_CODE: ENC[AES256_GCM,data:6LgT+FKUgq0hlJTdFHGFyrl6vMQ2bmkUWfFfMd4Arik=,iv:5xM7GQs/sHr1JfOTGsrG/nWzpGlwVfja2BUcPRSLlbA=,tag:IuuHwHJgC8IxgFUfxccQ1g==,type:str]
sops:
    age:
        - enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcVc4WjV5OUsvOWUrbktP
              ZFRuaEhKdUF3VGFnUlBpQkR6bG1IMTZTeFJFClp0Sk5mcUJVbDgwckNWaEs2U1BF
              azQrSmtxNy8rYTBNbWN6Z2IyZ0paR0EKLS0tIDBXeFhlZldYNHVoQmZKTVN6ZWYv
              Z092LzM5bDBIdkROc2tVcWhWRGxzU1UKmujgJ4CA4/QktUw686+ju5f7cDHf6IrR
              r/o+AWQcljPu1pyyc+9uVX4Q1Op6AyS2OZhlwwuX9NcJccmuf50Vsw==
              -----END AGE ENCRYPTED FILE-----
          recipient: age1s230vj65pqugtzgwt3d9rh0dymz80ucxt39aq6a8mt8egkp7yqeqpjawc6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T17:56:19Z"
    mac: ENC[AES256_GCM,data:KqxOdQIHBwd2fJboENT0OU2M5gmqKpqq4WtsiCs3oIZ6f2rvxdk3v9kFjcsKnlMGZMLqKxlzHaGWXcuQSnXlrAtiX3I4CtnTQ+56BWpZKKuRQYc7P3Sk7PcdYSfPiXnpPqPpCc8d9tT+QeRr036sYyrh0cnQQbjanbpcglOdVaM=,iv:6UYudLpQhezxADrZyZzIPBmScO6bC5WguuQw15tKYQ0=,tag:TsB9uOBGJOmoCeN9rURYOQ==,type:str]
    version: 3.13.3
