apiVersion: apps/v1
kind: Deployment

metadata:
    name: prometheus

spec:
    replicas: 1
    strategy:
        type: Recreate
    selector:
        matchLabels:
            app: prometheus
    template:
        metadata:
            labels:
                app: prometheus
        spec:
            enableServiceLinks: false
            serviceAccountName: prometheus
            containers:
                - name: prometheus
                  image: docker.io/prom/prometheus:latest@sha256:5ce7540c3c00ef4ab0c9d2c995c6a5b9c421f44b4a115d97a2c7af3b1c21cbb0
                  args:
                      - "--config.file=/etc/prometheus/prometheus.yml"
                      - "--storage.tsdb.path=/prometheus"
                      - "--storage.tsdb.retention.time=30d"
                  ports:
                      - name: http
                        containerPort: 9090
                  resources:
                      requests:
                          cpu: 100m
                          memory: 512Mi
                      limits:
                          memory: 2Gi
                  volumeMounts:
                      - name: prometheus
                        mountPath: /prometheus
                      - name: prometheus-config
                        mountPath: /etc/prometheus/prometheus.yml
                        subPath: configuration.yaml
                        readOnly: true
            volumes:
                - name: prometheus
                  hostPath:
                      path: /var/data/local/prometheus
                      type: Directory
                - name: prometheus-config
                  configMap:
                      name: prometheus-config
