apiVersion: apps/v1
kind: Deployment

metadata:
    name: n8n

spec:
    replicas: 1
    strategy:
        type: Recreate
    selector:
        matchLabels:
            app: n8n
    template:
        metadata:
            labels:
                app: n8n
        spec:
            enableServiceLinks: false
            securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                fsGroup: 1000
            containers:
                - name: n8n
                  image: docker.io/n8nio/n8n:2.38.7@sha256:a8c95f75c6fdf65f5f2b7a7b354744eaa1c62bb911b5c00af6499c3f38e4cd32
                  env:
                      - name: N8N_PORT
                        value: "5678"
                      - name: N8N_HOST
                        value: n8n.wacky.homes
                      - name: N8N_PROTOCOL
                        value: https
                      - name: WEBHOOK_URL
                        value: https://n8n.wacky.homes/
                      - name: GENERIC_TIMEZONE
                        value: UTC
                      - name: TZ
                        value: UTC
                      - name: N8N_SECURE_COOKIE
                        value: "false"
                      - name: N8N_INSECURE_DISABLE_WEBHOOK_IFRAME_SANDBOX
                        value: "true"
                      - name: N8N_PROXY_HOPS
                        value: "2"
                      - name: N8N_RUNNERS_ENABLED
                        value: "true"
                      - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
                        value: "true"
                      - name: N8N_DIAGNOSTICS_ENABLED
                        value: "false"
                  envFrom:
                      - secretRef:
                            name: n8n
                  ports:
                      - name: http
                        containerPort: 5678
                  resources:
                      requests:
                          cpu: 100m
                          memory: 256Mi
                      limits:
                          memory: 1Gi
                  volumeMounts:
                      - name: data
                        mountPath: /home/node/.n8n
            volumes:
                - name: data
                  hostPath:
                      path: /var/data/local/n8n
                      type: Directory
