apiVersion: v1
kind: Secret
metadata:
    name: n8n
type: Opaque
stringData:
    #ENC[AES256_GCM,data:xk87ZRrGLSK5jfSwbuLT9xhac4Oj0433jnLvc+4SGSpyfvmthMXsNoTt1m7vIfIzSFA7x8P5hsp6EiVqpgykBY6N,iv:jeID7mjXW6MZeSCHDBuLkT5iCZKd24Z5hjpN4Y2iFl4=,tag:AVRrS6qpRKk9EThchz4gVw==,type:comment]
    #ENC[AES256_GCM,data:AXStVeD5kZtrGXm0oHFndST//0wwtzVsmwjPrLNVA2LmzRYEf5aBm5rRN0b+xNoN4ALsFhvoE2O6tLHsbWbMYzcPKuasAg==,iv:0Wh0xzA4GBKmKDU/cuNJ/MtRCrz7YCJDpSaP/WVYoOo=,tag:0rm/Krx5/19PVJMFBORhAA==,type:comment]
    #ENC[AES256_GCM,data:6314jS+r+0HZkLQWNUsYiG3fpv+rvJCz2WugWls4,iv:Ri90YNJVDq5Bd+6aYSqIzaGIY6bbBQkMwRtr0G42Xz4=,tag:DuGz/+PN5Mu8e3M6yIHr4w==,type:comment]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:U6eyvSwnv1cHa+4gj2EDlfCYE/CVpTzvSetnkNnZK4zu8j8YeLaO3BQE4jsbICaF1vJ9suEgz1VRZwQRd2eZxg==,iv:lbqqE+Q+0r0JWbGN65Vg+QBbwtAaawj8uG7YyVk8WaU=,tag:/WhlSf+x6UxNbI2vOWvwcA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTV1RJdmQ2eVZ4dFFESFVz
            cmh3aEV0L3Jsa1VNY294ejlobk56aFRBaVhJCi9iN1VPNjRiaHU5NUQyUFBlOGVD
            a2FpdEttSWcvM2Q3dHN5YmJ2Zm4xVmcKLS0tIDF4TGZlWnc3SUdaOTNVZGU2L0hB
            M1pmSWc1bGl6Z2gyeGJCYjZEcUhHaUEKad4WF12oRdpxpXlyTYlehHiZwDydFcSN
            Kr+O849MtUIVq759ymY21qN9PadYE+Qmin9Qoxqzev7SeyWVtJ8i+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s230vj65pqugtzgwt3d9rh0dymz80ucxt39aq6a8mt8egkp7yqeqpjawc6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T10:12:53Z"
    mac: ENC[AES256_GCM,data:T9tIOEt/MIGK2VDFsY4fhJ/Hh7yUweWi4D3TYug1+aL9oPChzk6VtaHYkE3/g5bi8wa6efX+yyae+/Cb5GOjKV8zCcCEbq4bj0x+jWMYW9YlHSOgq7tT6BstFUQpHDBEBNC9H0FnbTrA6dVZAQ9TUZZgGz5a6KbPDkoGvR22XVU=,iv:a5IvO29+4U/0aKtuDReCzsjy/3ERfspLUaI/Y1QcWbE=,tag:gBzJHHaFUegtWwwjK8MxvQ==,type:str]
    version: 3.13.3
