apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
    name: applications
    namespace: flux-system

spec:
    # Check Git for changes every five minutes.
    interval: 5m

    # Apply files from this path in the Git repository.
    path: ./apps

    # Delete Kubernetes objects removed from Git.
    prune: true

    # Use the GitRepository created by flux bootstrap.
    sourceRef:
        kind: GitRepository
        name: flux-system

    # Wait for resources to become ready.
    wait: true
    timeout: 5m

    # Tell Flux to decrypt SOPS files using the "sops-age"
    # Kubernetes Secret in the flux-system namespace.
    decryption:
        provider: sops
        secretRef:
            name: sops-age
