apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
    namespace: default
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:k6bgLj1xfjc9s37pKMs59S7bK5Ozwv9jBAI81BtBKSeGlWZwEP5wl8upWa3yvKNHXjXEW5vEGf1Fy9QlLucHjXhwat08E7uOuscyKnVwz4iUqUYXY/vBYS2+LexUnAOPfHzgLo49IdHUBG5cN7cwyH1oxfgK62CdW6y+TB/1jYH5oTGIAy/9jS3T8d7m8hgbJhB021puZDzw7p8HpNxsHYDr9E2AzDf0BkD3GZ0neH0ved26H1migw==,iv:6m9WT9g1zEr615o2ponO092WvumwQRetV3HR52zSz58=,tag:cyDYsKprTpiGH7bSADU+Uw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1THJKS1prenVpdzArL1Fx
            WDJybzQ4Rm0zR3RFWlJlRjZDRlZ2ZmZ4QXk4Cjg2L3h0YW5zY2J3WWtlcC9lWFhj
            RXN2Z3A4OE9pZ3RScUxyOWcyODZaV28KLS0tIGM1KzNqSXliZ2lsVGRGR3Y5SEhu
            VEwzM2VKcUxHSWpOOG12Nk12c21id2sKTjUuAT0M7i3glBguv7Qfz4vYShB1froF
            VtQnDcQg/5l3QawQTGnPs/5P3oq2YN3jINpsG+C71fFXL4S6d763nw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s230vj65pqugtzgwt3d9rh0dymz80ucxt39aq6a8mt8egkp7yqeqpjawc6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T13:34:00Z"
    mac: ENC[AES256_GCM,data:1HN+cMewG35pVuHOt+6vDfnJaBxaaXtvanku9TJeCig7ZjAQUn+crmZO1tzrZVguhD9mobHwAXoBp7a/NKC7hUdh+FyJMNEbFiHnp0e0xkwJ3piNfXYK2+wyOjaNcHbAgerq1V8K/k5jLWneyZ7JfKUQ4QTMZV3kfLM/dbay9YI=,iv:ufUyH4OMhMLwItTGyd2IfYSNcyXS4QULEtXLfm7USVg=,tag:fF7Skm7imJ2MtU0I8Mb5+Q==,type:str]
    version: 3.13.3
