[[customizations.filesystem]]
mountpoint = "/"
minsize = "450 GiB"

[[customizations.user]]
name = "wacky"
password = "" # openssl passwd -6 "your-password"
groups = ["wheel"]
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFmtibYVCi69k/aIbsn7LRagPrvwJwaHxLODkn4UGqNn wacky"
